### ISSUE TITLE
Show the profile switcher but not the Input field saying Choose starting place, and choose destination.

### ISSUE THREAD

**Issue by aasutossh** [mapbox/mapbox-gl-directions#263]
```controls: {
          profileSwitcher: true,
          inputs: false,
          // instructions: false,
        },```
disables the profile switcher too.

**Comment by aasutossh** [comment]
So, I did a bit inspecting and did 
```css
.mapbox-directions-origin,
.mapbox-directions-destination {
  display: none;
}
```
